### PR TITLE
Implement DEP-11 MediaBaseUrl support

### PR DESCRIPTION
**Pull request by robert-ancell**
This is in the DEP-11 spec:
https://www.freedesktop.org/software/appstream/docs/sect-AppStream-DEP11.html#spec-dep11-general

See https://github.com/hughsie/appstream-glib/issues/70

### CODE REVIEW

**Comment by robert-ancell** [comment]
This is in the DEP-11 spec:

**Comment by robert-ancell** [comment]
#https://github.com/hughsie/appstream-glib/issues/70

**Comment by robert-ancell** [comment]
(I don't have write access, so I can't merge this myself).

**Comment by hughsie** [comment]
You do now :)

**Pull request merged**
