### PR TITLE
Make as_app_kind_to_string output current names of enumerated values

### PR DESCRIPTION
**Pull request by robert-ancell**
The values were changed in ea8b160c8f05ae018dcf54181204cc5740c2aa1c

### CODE REVIEW

**Comment by hughsie** [comment]
I thought about this; if we do this then we'll create metadata that older versions of appstream-glib can't process. I think we can merge this, bu maybe not just yet.

**Comment by ximion** [comment]
If this gets merged, we can also switch the default install path for metainfo files to `/usr/share/metainfo`, since that path has been supported for a really long time now (much longer than the component names).
But whatever works best for your schedule is fine :-) - there is no rush to update.

**Comment by robert-ancell** [comment]
I'll leave this PR open so people know about the reason for the current code. Feel free to merge when it's appropriate to do so.

**Comment by ximion** [comment]
It's important to note that while the AppStream reference implementation has a fallback for `desktop` <-> `desktop-application`, this does not happen for `webapp`, because unlike `desktop`, `webapp` was never a recognized component type name in AppStream.
So, without this change, appstream-glib might generate invalid AppStream metadata.

**Pull request closed without merging**
