### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by Alexmelman88**

### CODE REVIEW

**Comment by hughsie** [comment]
Can you submit the translation through http://www.transifex.com/ please?

**Comment by Alexmelman88** [comment]
I am a member of the translation team on Damned Lies. https://l10n.gnome.org/module/appstream-glib/ It says to create a pull request. I am not registered at http://www.transifex.com/. Can you accept these changes ?

**Comment by Alexmelman88** [comment]
From [README.md](https://github.com/hughsie/appstream-glib#readme) https://www.transifex.com/projects/p/appstream-glib/ does not exist, only possibility to update the translation is PR.

**Comment by hughsie** [comment]
Okay, fair enough. Thanks!

**Pull request merged**
