### PR TITLE
as-app-desktop: Fix association between icon names and types

### PR DESCRIPTION
**Pull request by pwithnall**
AsIcon documents that STOCK icons should have the name set; and that
LOCAL icons should have the filename set. The previous approach to
extracting these properties from as_app_parse_file_key() could sometimes
result in a LOCAL icon with no filename set, if tmp was not an icon name
and not a fallback icon name. Now, we assume that (as long as tmp is not
an absolute path) this means it's an icon name for an icon which is not
installed, and hence the AsIcon type should be STOCK.

Signed-off-by: Philip Withnall <philip.withnall@collabora.co.uk>

### CODE REVIEW

**Comment by hughsie** [comment]
Does this allow make check to pass? Thanks.

**Comment by pwithnall** [comment]
> Does this allow make check to pass? Thanks.

Yup, `make check` passes before and after applying the branch — which means that there aren’t any tests which actually cover this particular bit of the icon functionality.

**Comment by hughsie** [comment]
This breaks make check in libappstream-builder

**Comment by pwithnall** [comment]
Eh? It definitely worked for me. I’ll take a look soon and try and work out what went wrong. :-(

**Comment by pwithnall** [comment]
I’ve just tested again (with the patch applied against master as of now) and `make check` in libappstream-builder does work for me. What failure are you getting?
> jhbuild:~/.cache/jhbuild/build/appstream-glib/libappstream-builder $ make check
> Making check in plugins
> make[1]: Entering directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder/plugins'
> make[1]: Nothing to be done for 'check'.
> make[1]: Leaving directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder/plugins'
> make[1]: Entering directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> make  asb-self-test
> make[2]: Entering directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> make[2]: 'asb-self-test' is up to date.
> make[2]: Leaving directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> make  check-TESTS
> make[2]: Entering directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> make[3]: Entering directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> PASS: asb-self-test
> ============================================================================
> Testsuite summary for appstream-glib 0.6.3
> ============================================================================
> # TOTAL: 1
> # PASS:  1
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  0
> # XPASS: 0
> # ERROR: 0
> ============================================================================
> make[3]: Leaving directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> make[2]: Leaving directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'
> make[1]: Leaving directory '/home/philip/.cache/jhbuild/build/appstream-glib/libappstream-builder'

**Comment by hughsie** [comment]
I get this:

    Asb:ERROR:asb-self-test.c:567:asb_test_context_test_func: assertion failed (error == NULL): --- /tmp/b	2016-09-04 08:27:19.593418924 +0100
    @@ -67,7 +67,7 @@
     <name>App</name>
     <summary>A test application</summary>
     <description><p>Long description goes here.</p></description>
    -<icon type="cached" height="64" width="64">app.png</icon>
    +<icon type="stock">app</icon>
     <categories>
     <category>Profiling</category>
     <category>System</category>

**Comment by hughsie** [comment]
Is this working how you expect now? Thanks.

**Comment by pwithnall** [comment]
The patches look like they should do the trick, but it will take me a little while to test (need to backport the patches to a Debian package on a different machine then test). I’ll let you know. Thanks!

**Comment by pwithnall** [comment]
I just got a chance to test it, and your fixes do the job. Thanks!

**Pull request merged**
