### PR TITLE
Fix the build with gperf 3.1

### PR DESCRIPTION
**Pull request by kalev**

### CODE REVIEW

**Comment by kalev** [comment]
An alternative way to fix this would be to add a configure check to detect the function signature, similar to how is done in https://github.com/systemd/systemd/commit/c9f7b4d356a453a01aa77a6bb74ca7ef49732c08

**Comment by hughsie** [comment]
Could we do the 3rd section fix like https://github.com/libguestfs/libguestfs/commit/004de6cf45cfe66ca166cbdcb1c3125a2a81eb31 ?

Richard.

**Comment by kalev** [comment]
You mean merge as-tag.c and as-tag.gperf together into one file?

**Comment by hughsie** [comment]
Well, if we do that it's a bit more tricky to support with-and-without gperf. Ideally not all of as-tag.c, but just _as_tag_from_gperf()

**Comment by kalev** [comment]
Pushed a new approach that follows what systemd is doing after our irc discussion.

**Pull request merged**
